# Generated by Django 4.1 on 2023-04-14 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AplicacionTapizados', '0002_administrador'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseMueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.IntegerField()),
                ('Estado', models.CharField(max_length=100)),
                ('Material', models.CharField(max_length=100)),
                ('TipoPatas', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreCliente', models.CharField(max_length=100)),
                ('Rut', models.CharField(max_length=20)),
                ('Direccion', models.CharField(max_length=100)),
                ('Correo', models.CharField(max_length=100)),
                ('Comuna', models.CharField(max_length=100)),
                ('Telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaPedido', models.DateTimeField()),
                ('NumeroPedido', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AplicacionTapizados.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreVendedor', models.CharField(max_length=100)),
                ('Rut', models.CharField(max_length=20)),
                ('Local', models.CharField(max_length=100)),
                ('FechaIngreso', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TipoProducto', models.CharField(max_length=100)),
                ('NombreTela', models.CharField(max_length=100)),
                ('Color', models.CharField(max_length=100)),
                ('CantidadTela', models.CharField(max_length=100)),
                ('RellenoNuevo', models.CharField(max_length=10)),
                ('CojinesRespaldo', models.IntegerField()),
                ('CojinesAsiento', models.IntegerField()),
                ('ValorEstimado', models.IntegerField()),
                ('ValorFinal', models.IntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AplicacionTapizados.pedido')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AplicacionTapizados.vendedor'),
        ),
        migrations.CreateModel(
            name='DetalleProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreVendedor', models.CharField(max_length=100)),
                ('NombreCliente', models.CharField(max_length=100)),
                ('NumeroCliente', models.IntegerField()),
                ('FechaPedido', models.DateTimeField()),
                ('TipoProducto', models.CharField(max_length=100)),
                ('NombreTela', models.CharField(max_length=100)),
                ('Color', models.CharField(max_length=100)),
                ('CantidadTela', models.CharField(max_length=100)),
                ('RellenoNuevo', models.CharField(max_length=10)),
                ('CojinesRespaldo', models.IntegerField()),
                ('CojinesAsiento', models.IntegerField()),
                ('Cantidad', models.IntegerField()),
                ('Estado', models.CharField(max_length=100)),
                ('Material', models.CharField(max_length=100)),
                ('TipoPatas', models.CharField(max_length=100)),
                ('ValorFinal', models.IntegerField()),
                ('baseMueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AplicacionTapizados.basemueble')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AplicacionTapizados.cliente')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AplicacionTapizados.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AplicacionTapizados.producto')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AplicacionTapizados.vendedor')),
            ],
        ),
        migrations.AddField(
            model_name='basemueble',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AplicacionTapizados.producto'),
        ),
    ]
